name: vivek_yadav
description: "Showcase the impressive career of Vivek Yadav, a Google Developer Expert for Flutter and Dart, with a modern, enterprise-grade portfolio website highlighting his expertise in mobile architecture, leadership, and community impact."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  url_launcher: ^6.0.0
  provider: ^6.0.0
  animate_do: ^4.0.0
  responsive_framework: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
